### ISSUE TITLE
Use inputs rather than env vars

### ISSUE THREAD

**Issue by jroper** [lightbend/kalix-action#13]
We should pass the token and project using inputs rather than environment variables, eg:

```yaml
inputs:
  kalix-token:
    description: 'Kalix service token'
    default: '${{ secrets.kalix-token }}'
  kalix-project:
    description: 'Kalix project'
    default: '${{ secrets.kalix-project }}'
```

Note that I'm not 100% sure if you can reference secrets from the default value for a parameter, but we should check, because it would be very convenient if you can.
